language: ruby
rvm:
  - 2.4.1
dist: trusty
sudo: required
services: mysql
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - haveged
      - google-chrome-stable
      - chromium-chromedriver
cache: bundler
bundler_args: --without warehouse deployment
env:
  matrix:
    - "DB_REQUIRED='true' RAILS_ENV=test TZ=Europe/London SUITE='rake test' RUBYOPT='-W0'" # RUBYOPT disables warnings turned on by default in rake 11. See note in README
    - "DB_REQUIRED='true' RAILS_ENV=test TZ=Europe/London SUITE='rspec'"
    - "DB_REQUIRED='true' RAILS_ENV=cucumber CI_NODE_TOTAL=2 CI_NODE_INDEX=0 JRUBY_OPTS='' PRECOMPILE_ASSETS=true CUCUMBER_FORMAT=DebugFormatter TZ=Europe/London SUITE='rake knapsack:cucumber'"
    - "DB_REQUIRED='true' RAILS_ENV=cucumber CI_NODE_TOTAL=2 CI_NODE_INDEX=1 JRUBY_OPTS='' PRECOMPILE_ASSETS=true CUCUMBER_FORMAT=DebugFormatter TZ=Europe/London SUITE='rake knapsack:cucumber'"
    - "SUITE=rubocop"
before_script:
  - 'mv config/aker.yml.example config/aker.yml'
  - 'export PATH=$PATH:/usr/lib/chromium-browser/'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'if [[ "$DB_REQUIRED" == "true" ]]; then bundle exec rake db:setup; fi'
  - 'if [[ "$PRECOMPILE_ASSETS" == "true" ]]; then bundle exec rake assets:precompile; fi'
script:
  - "bundle exec $SUITE"
