language: ruby
rvm:
  - 2.4.1
dist: trusty
sudo: required
services: mysql
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - haveged
      - google-chrome-stable
      - chromium-chromedriver
cache: bundler
bundler_args: --without warehouse deployment
env:
  global:
    - TZ=Europe/London
    - CUCUMBER_FORMAT=DebugFormatter
    - 'PATH=$PATH:/usr/lib/chromium-browser/'
    - 'DISPLAY=:99.0'
before_install:
  - 'mv config/aker.yml.example config/aker.yml'
  - 'sh -e /etc/init.d/xvfb start'
script:
  - "bundle exec $SUITE"
jobs:
  include:
    # Cron task runs all tests in a single ~50m task for coverage specs
  - if: type = cron
    script: './run_coverage'
    before_script:
    - 'curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter'
    - 'chmod +x ./cc-test-reporter'
    - './cc-test-reporter before-build'
    after_script:
    - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
    # Rubocop
  - if: type != cron
    env: SUITE=rubocop
    # Minitest
  - if: type != cron
    env:
    - "SUITE='rake test'"
    - 'RAILS_ENV=test'
    - "RUBYOPT='-W0'"
    before_script:
    - bundle exec rake db:setup
    script: bundle exec rake test
    # Rspec
  - if: type != cron
    env:
    - 'SUITE=rspec'
    - 'RAILS_ENV=test'
    before_script:
    - bundle exec rake db:setup
    # Cucumber node 0
  - if: type != cron
    env:
    - "SUITE='rake knapsack:cucumber'"
    - 'RAILS_ENV=cucumber'
    - CI_NODE_TOTAL=2
    - CI_NODE_INDEX=0
    before_script:
    - bundle exec rake assets:precompile
    - bundle exec rake db:setup
    # Cucumber node 1
  - if: type != cron
    env:
    - "SUITE='rake knapsack:cucumber'"
    - 'RAILS_ENV=cucumber'
    - CI_NODE_TOTAL=2
    - CI_NODE_INDEX=1
    before_script:
    - bundle exec rake assets:precompile
    - bundle exec rake db:setup
